version: "3.9"
services:
  laravel.tersea:
    build:
      context: ./vendor/laravel/sail/runtimes/8.1
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: sail-8.1/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - ".:/var/www/html"
    networks:
      - sail_tersea
networks:
  sail_tersea:
    name: sail
    external: true
